### ISSUE TITLE
Importing mssql failover group secondary database is destructive

### ISSUE THREAD

**Issue by erniebilling** [terraform-providers/terraform-provider-azurerm#11024]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.12.26
AzureRM provider 2.51.0

### Affected Resource(s)

* `azurerm_mssql_database`
* `azurerm_sql_failover_group`

#### Example Failover Group to reproduce problem:
For reproduction purposes, this terraform will create a failover group that will illustrate the problem:
```hcl
variable instance_name { 
    type = string
    default = "test-mssql-db" 
}
variable resource_group { 
    type = string
    default = "test-mssql-db-rg" 
}
variable db_name { 
    type = string
    default = "test-db"
}
variable location { 
    type = string 
    default = "eastus2"
}
variable labels { 
    type = map
    default = {} 
}
variable sku_name { 
    type = string 
    default = "GP_Gen5_2"
}
variable max_storage_gb { 
    type = number 
    default = 10
}

provider "azurerm" {
  version = "~> 2.51.0"
  features {}
}

resource "azurerm_resource_group" "azure-sql-fog" {
  name     = var.resource_group
  location = var.location
  tags     = var.labels
}

resource "random_string" "username" {
  length = 16
  special = false
  number = false
}

resource "random_password" "password" {
  length = 64
  override_special = "~_-."
  min_upper = 2
  min_lower = 2
  min_special = 2
}

resource "azurerm_sql_server" "primary_azure_sql_db_server" {
  depends_on = [ azurerm_resource_group.azure-sql-fog ]
  name                         = format("%s-primary", var.instance_name)
  resource_group_name          = var.resource_group
  location                     = var.location
  version                      = "12.0"
  administrator_login          = random_string.username.result
  administrator_login_password = random_password.password.result
  tags = var.labels
}

locals {
  default_pair = {
    // https://docs.microsoft.com/en-us/azure/best-practices-availability-paired-regions
    "eastasia" = "southeastasia"
    "southeastasia" = "eastasia"
    "centralus" = "eastus2"
    "eastus" = "westus"
    "eastus2" = "centralus"
    "westus" = "eastus"
    "northcentralus" = "southcentralus"
    "southcentralus" = "northcentralus"
    "northeurope" = "westeurope"
    "westeurope" = "northeurope"
    "japanwest" = "japaneast"
    "japaneast" = "japanwest"
    "brazilsouth" = "southcentralus"
    "australiaeast" = "australiasoutheast"
    "australiasoutheast" = "australiaeast"
    "australiacentral" = "australiacentral2"
    "australiacentral2" = "australiacentral"
    "southindia" = "centralindia"
    "centralindia" = "southindia"
    "westindia" = "southindia"
    "canadacentral" = "canadaeast"
    "canadaeast" = "canadacentral"
    "uksouth" = "ukwest"
    "ukwest" = "uksouth"
    "westcentralus" = "westus2"
    "westus2" = "westcentralus"
    "koreacentral" = "koreasouth"
    "koreasouth" = "koreacentral"
    "francecentral" = "francesouth"
    "francesouth" = "francecentral"
    "uaenorth" = "uaecentral"
    "uaecentral" = "uaenorth"
    "southafricanorth" = "southafricawest" 
    "southafricawest" = "southafricanorth"
    "germanycentral" = "germanynortheast"
    "germanynortheast" = "germanycentral"
  }   
}

resource "azurerm_sql_server" "secondary_sql_db_server" {
  depends_on = [ azurerm_resource_group.azure-sql-fog ]
  name                         = format("%s-secondary", var.instance_name)
  resource_group_name          = var.resource_group
  location                     = local.default_pair[var.location]
  version                      = "12.0"
  administrator_login          = random_string.username.result
  administrator_login_password = random_password.password.result
  tags                         = var.labels
}

resource "azurerm_mssql_database" "azure_sql_db" {
  name                = var.db_name
  server_id           = azurerm_sql_server.primary_azure_sql_db_server.id
  sku_name            = var.sku_name
  max_size_gb         = var.max_storage_gb
  tags                = var.labels
}

resource "azurerm_sql_failover_group" "failover_group" {
  depends_on = [ azurerm_resource_group.azure-sql-fog ]
  name                = var.instance_name
  resource_group_name = var.resource_group
  server_name         = azurerm_sql_server.primary_azure_sql_db_server.name
  databases           = [azurerm_mssql_database.azure_sql_db.id]
  partner_servers {
    id = azurerm_sql_server.secondary_sql_db_server.id
  }

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 5
  }
}

output primary_server_name { value = azurerm_sql_server.primary_azure_sql_db_server.name }
output secondary_server_name { value = azurerm_sql_server.secondary_sql_db_server.name }
output failover_group_name { value = azurerm_sql_failover_group.failover_group.name }
output resource_group { value = var.resource_group }
output db_name { value = azurerm_mssql_database.azure_sql_db.name }
```
#### Terraform to import resulting failover group
*provider.tf*
```hcl
provider "azurerm" {
  version = "~> 2.51.0"
  features {}
}
```
*main.tf*
```hcl
resource "azurerm_mssql_database" "primary_db" {
}

resource "azurerm_mssql_database" "secondary_db" {
}

resource "azurerm_sql_failover_group" "failover_group" {
}
```
### Expected Behaviour

Once `terraform import` for the three resources is complete and the resulting terraform is cleaned `terraform apply` (with an update to the tags) should result in 0 to add, 1 to change, 0 to destroy

### Actual Behaviour

If the secondary db has a `create_mode` of *Secondary*, the db is destroyed and recreated.

if the secondary db does not have a `create_mode` of *Secondary*, the apply fails with 

```
Error: failure in issuing create/update request for SQL Database "test-db" Blob Auditing Policies(SQL Server "test-mssql-db-secondary"/ Resource Group "test-mssql-db-rg"): sql.ExtendedDatabaseBlobAuditingPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BlobAuditingIsNotSupportedOnGeoDr" Message="Blob auditing can be configured on primary databases only."bash
```

#### Create an example failover group

Use the *Example Failover Group to reproduce problem* segment above to create a failover group and get the Azure ID's for the resources
```bash
terraform init
terraform apply
export PRIMARY_DB_ID=$(az sql failover-group show --name $(terraform output failover_group_name | tr -d '\n\r') --server $(terraform output primary_server_name | tr -d '\n\r') --resource-group $(terraform output resource_group | tr -d '\n\r') --query databases[0] -o tsv)
export SECONDARY_DB_ID=$(az sql failover-group show --name $(terraform output failover_group_name | tr -d '\n\r') --server $(terraform output secondary_server_name | tr -d '\n\r') --resource-group $(terraform output resource_group | tr -d '\n\r') --query databases[0] -o tsv)
export FOG_ID=$(az sql failover-group show --name $(terraform output failover_group_name | tr -d '\n\r') --server $(terraform output primary_server_name | tr -d '\n\r') --resource-group $(terraform output resource_group | tr -d '\n\r') --query id -o tsv)
```

#### Import the failover group and db's

In a new directory, put *provider.tf* and *main.tf* files from above, import the db's and failover group, and use show to get the updated *main.tf*

```bash
terraform init
terraform import azurerm_mssql_database.primary_db ${PRIMARY_DB_ID}
terraform import azurerm_mssql_database.secondary_db ${SECONDARY_DB_ID}
terraform import azurerm_sql_failover_group.failover_group ${FOG_ID}
mv main.tf main.tf.orig
terraform show -no-color > main.tf
```

#### Clean out the new main.tf
Some values are readonly and can't be applied.

Remove or comment out the following from *main.tf*
* azurerm_mssql_database.primary_db.id
* azurerm_mssql_database.primary_db.long_term_retention_policy
* azurerm_mssql_database.secondary_db.id
* azurerm_mssql_database.secondary_db.long_term_retention_policy
* azurerm_sql_failover_group.failover_group.id
* azurerm_sql_failover_group.failover_group.location
* azurerm_sql_failover_group.failover_group.role
* azurerm_sql_failover_group.failover_group.partner_servers.location
* azurerm_sql_failover_group.failover_group.partner_servers.role

#### Attempt to apply
```bash
terraform apply
```

Should fail with 
```bash
Error: failure in issuing create/update request for SQL Database "test-db" Blob Auditing Policies(SQL Server "test-mssql-db-secondary"/ Resource Group "test-mssql-db-rg"): sql.ExtendedDatabaseBlobAuditingPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BlobAuditingIsNotSupportedOnGeoDr" Message="Blob auditing can be configured on primary databases only."
```

#### Change `create_mode` to *Secondary*
Add the following to `azurerm_mssql_database.secondary_db`:
```
    create_mode = "Secondary"
```

Run `terraform plan` and it'll want to destroy and recreate the db, which is very unwanted.

```bash
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

azurerm_sql_failover_group.failover_group: Refreshing state... [id=/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg/providers/Microsoft.Sql/servers/test-mssql-db-primary/failoverGroups/test-mssql-db]
azurerm_mssql_database.primary_db: Refreshing state... [id=/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg/providers/Microsoft.Sql/servers/test-mssql-db-primary/databases/test-db]
azurerm_mssql_database.secondary_db: Refreshing state... [id=/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg/providers/Microsoft.Sql/servers/test-mssql-db-secondary/databases/test-db]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_mssql_database.secondary_db must be replaced
-/+ resource "azurerm_mssql_database" "secondary_db" {
        auto_pause_delay_in_minutes = 0
        collation                   = "SQL_Latin1_General_CP1_CI_AS"
      + create_mode                 = "Secondary" # forces replacement
      + creation_source_database_id = (known after apply)
        extended_auditing_policy    = []
      ~ id                          = "/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg/providers/Microsoft.Sql/servers/test-mssql-db-secondary/databases/test-db" -> (known after apply)
        license_type                = "LicenseIncluded"
        max_size_gb                 = 10
        min_capacity                = 0
        name                        = "test-db"
        read_replica_count          = 0
        read_scale                  = false
      + restore_point_in_time       = (known after apply)
      + sample_name                 = (known after apply)
        server_id                   = "/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg/providers/Microsoft.Sql/servers/test-mssql-db-secondary"
        sku_name                    = "GP_Gen5_2"
        storage_account_type        = "GRS"
        tags                        = {
            "creator" = "eb"
        }
        zone_redundant              = false

      ~ long_term_retention_policy {
          ~ monthly_retention = "PT0S" -> (known after apply)
          ~ week_of_year      = 0 -> (known after apply)
          ~ weekly_retention  = "PT0S" -> (known after apply)
          ~ yearly_retention  = "PT0S" -> (known after apply)
        }

        short_term_retention_policy {
            retention_days = 7
        }

      ~ threat_detection_policy {
          - disabled_alerts      = [] -> null
            email_account_admins = "Disabled"
          - email_addresses      = [] -> null
            retention_days       = 0
            state                = "Disabled"
          + use_server_default   = "Disabled"
        }

        timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Warning: "extended_auditing_policy": [DEPRECATED] the `extended_auditing_policy` block has been moved to `azurerm_mssql_server_extended_auditing_policy` and `azurerm_mssql_database_extended_auditing_policy`. This block will be removed in version 3.0 of the provider.

  on main.tf line 2, in resource "azurerm_mssql_database" "primary_db":
   2: resource "azurerm_mssql_database" "primary_db" {

(and one more similar warning elsewhere)


------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### Important Factoids

We have a few customers with many failover groups they would like to assume control over and this behavior is preventing the secondary db from being cleanly imported.

### References

Thought the `create_mode = "Secondary"` was a fix, but since it results in a re-creation of the secondary db, its not.

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/8892

**Comment by aristosvo** [comment]
I want to give this one a try by trying to recreate your scenario in an AccTest and go forward from there, but just to be clear:

You are triggering the creation of the secondary db by applying a failover group. This pattern is a bit different than the pattern in the example provided [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/cebabff02faac6684302a7a44c721cf0dc15ea9c/examples/sql-azure/failover_group/main.tf). Is there a particular reason to do so?

I'm not an export on secondary databases, that's the reason I'm asking, sorry if it is a stupid question :)

**Comment by aristosvo** [comment]
@erniebilling I've filled a PR of one line, it might fix your problem, it might not fix your problem. Do you know how to build a binary based on my branch/fork and test it?

The TDD approach is a bit limited from my side atm, as I ran out of credits again on my personal account because I forgot to turn of some expensive experimental stuff🤣

**Comment by erniebilling** [comment]
> I want to give this one a try by trying to recreate your scenario in an AccTest and go forward from there, but just to be clear:
> 
> You are triggering the creation of the secondary db by applying a failover group. This pattern is a bit different than the pattern in the example provided [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/cebabff02faac6684302a7a44c721cf0dc15ea9c/examples/sql-azure/failover_group/main.tf). Is there a particular reason to do so?
> 
> I'm not an export on secondary databases, that's the reason I'm asking, sorry if it is a stupid question :)

This is a case where we're trying to import existing infrastructure that was created by another application. It relied on letting creation of the failover group trigger creation of the secondary db. I provided the terraform above to simulate the issue.

**Comment by aristosvo** [comment]
Seems like a use case which should be supported, as current Acceptance Test role in that way.

As mentioned before, I'm unable to test myself as I've run out of credits, but the bug should be fixed by the mentioned [PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/11026)

**Comment by aristosvo** [comment]
@erniebilling Just a heads-up, the fix is planned to be included in the next release, which is approximately next Friday.

To prevent possible import problems, I'd fill the field `create_mode` before the import, not after:

```hcl
resource "azurerm_mssql_database" "primary_db" {
}

resource "azurerm_mssql_database" "secondary_db" {
  create_mode = "Secondary"
}

resource "azurerm_sql_failover_group" "failover_group" {
}
```

**Comment by erniebilling** [comment]
I've tested the PR locally and it is still trying to delete/recreate the secondary when  `create_mode = "Secondary"` is set.

If `create_mode = "Secondary"` is not set, it still fails with:

```
Error: failure in issuing create/update request for SQL Database "test-db" Blob Auditing Policies(SQL Server "test-mssql-db-secondary"/ Resource Group "test-mssql-db-rg"): sql.ExtendedDatabaseBlobAuditingPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BlobAuditingIsNotSupportedOnGeoDr" Message="Blob auditing can be configured on primary databases only."
```

Here is the output from `terraform plan` when `create_mode = "Secondary"` is included.

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_mssql_database.secondary_db must be replaced
-/+ resource "azurerm_mssql_database" "secondary_db" {
        auto_pause_delay_in_minutes = 0
        collation                   = "SQL_Latin1_General_CP1_CI_AS"
      + create_mode                 = "Secondary" # forces replacement
      + creation_source_database_id = (known after apply)
        extended_auditing_policy    = []
      ~ id                          = "/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg/providers/Microsoft.Sql/servers/test-mssql-db-secondary/databases/test-db" -> (known after apply)
        license_type                = "LicenseIncluded"
        max_size_gb                 = 10
        min_capacity                = 0
        name                        = "test-db"
        read_replica_count          = 0
        read_scale                  = false
      + restore_point_in_time       = (known after apply)
      + sample_name                 = (known after apply)
        server_id                   = "/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg/providers/Microsoft.Sql/servers/test-mssql-db-secondary"
        sku_name                    = "GP_Gen5_2"
        storage_account_type        = "GRS"
        tags                        = {
            "creator" = "eb"
        }
        zone_redundant              = false

      ~ long_term_retention_policy {
          ~ monthly_retention = "PT0S" -> (known after apply)
          ~ week_of_year      = 0 -> (known after apply)
          ~ weekly_retention  = "PT0S" -> (known after apply)
          ~ yearly_retention  = "PT0S" -> (known after apply)
        }

        short_term_retention_policy {
            retention_days = 7
        }

      ~ threat_detection_policy {
          - disabled_alerts      = [] -> null
            email_account_admins = "Disabled"
          - email_addresses      = [] -> null
            retention_days       = 0
            state                = "Disabled"
          + use_server_default   = "Disabled"
        }

        timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by aristosvo** [comment]
I had the opportunity to test your setup, and it doesn't work yet as expected.

Unfortunately the `create_mode` is not exposed in the Azure API as far as I can see, so it's more advanced than I expected it to be to implement the fix.

**Comment by winnab** [comment]
Hi @aristosvo! I'm working with @erniebilling as the eng manager on this issue. I wanted to check my understanding on your latest comment. Is extending the Azure API to include the `create_mode` property a possibility? Or are there other workarounds we can explore to get this functionality? Any help would be great as we have folks trying to get to production who are blocked on this. Thanks in advance!

**Comment by aristosvo** [comment]
Hi @winnab! 

To answer your question: yes, extending the Azure API to return the content of  `create_mode` property is a possibility. Currently this property is [only exposed on create AFAIK](https://github.com/Azure/azure-rest-api-specs/issues/1604), but as the create is indirect we don't have the ability to register it in our state during an import. Returning this property always would make the fix for this problem a lot easier. I'm neither a Hashicorp nor Microsoft employee, so the timelines for including this and releasing it as part of an API version are unknown to me, but are probably longer than wanted in case of a real blocking issue. 

The possibilities for a fix are currently discussed [in the PR for this issue](https://github.com/terraform-providers/terraform-provider-azurerm/pull/11026), the easiest fix would probably be to make `create_mode` a changeable variable in the Azure Terraform Provider. The dirty fix would be to change `create_mode` in your Terraform state.

**Comment by winnab** [comment]
Hey @aristosvo! 

Thanks for getting back to me. You're right, the first option probably isn't best for our timeline of this issue. However, it seems pretty useful to have exposed, and we have other customers who are using the broker and would benefit. Is this something we need to raise as a request for the Azure API or is that happening already? 

Thanks for outlining the possible fixes. Ernie is away this week, so I'm just wondering one more thing. From my understanding, the fixes in the provider or our state could result in a destructive action as Ernie mentioned above. Is that not the case? 

Thanks for your help!
Winna

**Comment by aristosvo** [comment]
Hi @winnab,

I don't think raising it to the Azure API would be of much help here, as it is raised before and [then turned down as a design decision](https://github.com/Azure/azure-rest-api-specs/issues/1604). If you want to, be my guest, but I don't expect the response to be different this time.

I'm not sure if I understand you correctly, but the current state of the Azure Terraform provider causes a destructive action atm because of an issue with importing existing secondary databases. One of these aforementioned fixes would improve that AFAIK. Is this answering your question?

**Comment by erniebilling** [comment]
> Hi @winnab!
> 
> To answer your question: yes, extending the Azure API to return the content of `create_mode` property is a possibility. Currently this property is [only exposed on create AFAIK](https://github.com/Azure/azure-rest-api-specs/issues/1604), but as the create is indirect we don't have the ability to register it in our state during an import. Returning this property always would make the fix for this problem a lot easier. I'm neither a Hashicorp nor Microsoft employee, so the timelines for including this and releasing it as part of an API version are unknown to me, but are probably longer than wanted in case of a real blocking issue.
> 
> The possibilities for a fix are currently discussed [in the PR for this issue](https://github.com/terraform-providers/terraform-provider-azurerm/pull/11026), the easiest fix would probably be to make `create_mode` a changeable variable in the Azure Terraform Provider. The dirty fix would be to change `create_mode` in your Terraform state.

Is there work in progress to make `create_mode` changeable? Will this fix the problem?

**Comment by aristosvo** [comment]
I need some direction from one of the maintainers how to proceed and if my assumptions are correct. The assigned maintainer (@tombuildsstuff) is on holidays AFAIK, so we probably are waiting for him to return.

**Comment by erniebilling** [comment]
@aristosvo Any updates on this issue?

**Comment by erniebilling** [comment]
Still trying to recreate secondary db with 2.55.0:
```
      + create_mode                 = "Secondary" # forces replacement
```

**Comment by erniebilling** [comment]
I tried the [PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/11026) and it still wants to destroy and recreate.

**Comment by winnab** [comment]
@aristosvo Any updates on this issue?

**Comment by aristosvo** [comment]
@winnab No, I still need a review on the solution from one of the maintainers to implement it in the right direction.

**Comment by aristosvo** [comment]
@winnab @erniebilling I believe I have the right direction for now. PR is updated, but not tested against the set of AccTests available, will do that this week, probably tomorrow. If these succeed and manual testing shows no problem it might get merged soon.

**Comment by pivotal-marcela-campo** [comment]
Hi,
I've just tried this fix and it still doesn't work. I've tried with both versions `2.57.0` and `2.58.0` just in case. 

With this fix, after doing the import and removing all unsettable fields, if we make any changes (e.g, tags in all three resources), when doing `terraform plan` we get the expected output 

`Plan: 0 to add, 3 to change, 0 to destroy`

But then when doing the actual `terraform apply` we get the following error:

```
Error: 'creation_source_database_id' is required for create_mode Secondary

  on main.tf line 47, in resource "azurerm_mssql_database" "secondary_db":
  47: resource "azurerm_mssql_database" "secondary_db" {
```

I tried setting `creation_source_database_id` to the id of the primary database. Then when applying the changes we get back to square one.

`Plan: 1 to add, 0 to change, 1 to destroy.`


```
Terraform will perform the following actions:

  # azurerm_mssql_database.secondary_db must be replaced
-/+ resource "azurerm_mssql_database" "secondary_db" {
        auto_pause_delay_in_minutes = 0
        collation                   = "SQL_Latin1_General_CP1_CI_AS"
        create_mode                 = "Secondary"
      + creation_source_database_id = "/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg-1/providers/Microsoft.Sql/servers/fog-force-2-primary/databases/test-db-1" # forces replacement
        extended_auditing_policy    = []
        geo_backup_enabled          = true
      ~ id                          = "/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg-1/providers/Microsoft.Sql/servers/fog-force-2-secondary/databases/test-db-1" -> (known after apply)
        license_type                = "LicenseIncluded"
        max_size_gb                 = 10
        min_capacity                = 0
        name                        = "test-db-1"
        read_replica_count          = 0
        read_scale                  = false
      + restore_point_in_time       = (known after apply)
      + sample_name                 = (known after apply)
        server_id                   = "/subscriptions/899bf076-632b-4143-b015-43da8179e53f/resourceGroups/test-mssql-db-rg-1/providers/Microsoft.Sql/servers/fog-force-2-secondary"
        sku_name                    = "GP_Gen5_2"
        storage_account_type        = "GRS"
      ~ tags                        = {
          + "sometag" = "somevalue"
        }
        zone_redundant              = false

      ~ long_term_retention_policy {
          ~ monthly_retention = "PT0S" -> (known after apply)
          ~ week_of_year      = 0 -> (known after apply)
          ~ weekly_retention  = "PT0S" -> (known after apply)
          ~ yearly_retention  = "PT0S" -> (known after apply)
        }

      ~ short_term_retention_policy {
          ~ retention_days = 7 -> (known after apply)
        }

      ~ threat_detection_policy {
          ~ disabled_alerts            = [] -> (known after apply)
          ~ email_account_admins       = "Disabled" -> (known after apply)
          ~ email_addresses            = [] -> (known after apply)
          ~ retention_days             = 0 -> (known after apply)
          ~ state                      = "Disabled" -> (known after apply)
          + storage_account_access_key = (sensitive value)
          + storage_endpoint           = (known after apply)
          + use_server_default         = (known after apply)
        }

        timeouts {}
    }
```


@aristovo This definitely took us one step further, maybe this can be fixed in the same way the `creationMode` was?
It looks like the `creation_source_database_id` field is not changeable in the provider. One solution might be to also set it alongside the `createMode` [here](https://github.com/aristosvo/terraform-provider-azurerm/blob/2f0d6adf942396d412e46bf4e7b09afb9a6177b0/azurerm/internal/services/mssql/mssql_database_resource.go#L55) .

Thanks all for your help!

**Comment by aristosvo** [comment]
Ah, that's a bit of a pity. I overlooked this, sorry. The good news is that this is easy to change, as far as I can see now 🤣
