### ISSUE TITLE
Application Gateway : action_set parameter in rewrite_rule_set doesn't exist

### ISSUE THREAD

**Issue by rossifumax** [terraform-providers/terraform-provider-azurerm#11611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azurerm v2.51.0
```

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "network" {
  name                = "example-appgateway"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  sku {
    name     = "Standard_Small"
    tier     = "Standard"
    capacity = 2
  }

  gateway_ip_configuration {
    name      = "my-gateway-ip-configuration"
    subnet_id = azurerm_subnet.frontend.id
  }

  frontend_port {
    name = local.frontend_port_name
    port = 80
  }

  frontend_ip_configuration {
    name                 = local.frontend_ip_configuration_name
    public_ip_address_id = azurerm_public_ip.example.id
  }

  backend_address_pool {
    name = local.backend_address_pool_name
  }

  backend_http_settings {
    name                  = local.http_setting_name
    cookie_based_affinity = "Disabled"
    path                  = "/path1/"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 60
  }

  http_listener {
    name                           = local.listener_name
    frontend_ip_configuration_name = local.frontend_ip_configuration_name
    frontend_port_name             = local.frontend_port_name
    protocol                       = "Http"
  }

  request_routing_rule {
    name                       = local.request_routing_rule_name
    rule_type                  = "Basic"
    http_listener_name         = local.listener_name
    backend_address_pool_name  = local.backend_address_pool_name
    backend_http_settings_name = local.http_setting_name
  }

  rewrite_rule_set {
    name = "header-client-ip"
    rewrite_rule = {
      name          = "client-ip"
      rule_sequence = 100
      request_header_configuration = {
        header_name  = "Client-IP"
        header_value = "{var_client_ip}"
      }
    }
  }
}
```

### Debug Output
```
Error: creating/updating Application Gateway: (Name "my-appgw" / Resource Group "my-rg-appgw"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ApplicationGatewayRewriteRuleSetActionSetInRewriteRuleCannotBeEmpty" Message="ActionSet is a required field in a RewriteRule." Details=[]
```

### Expected Behaviour

The problem is that Azure API is clearly expecting an `action_set` parameter, but according to the documentation (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#rewrite_rule_set) and according to the provider code of the Application Gateway (https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/network/application_gateway_resource.go#L906), there isn't any reference of this parameter in the provider.

I think this parameter need to be added to the provider otherwise the `rewrite_rule_set` block is useless.

### Actual Behaviour

Actually, i can't apply my terraform code without an `ignore_changes` block on the `rewrite_rule_set` because of this missing parameter.

### Steps to Reproduce

1. `terraform apply`

### References

There are already issues that have been opened in the past without answers :

* #8897 : action_set in rewrite_rule not working
* #9135 : action_set not available in provider

**Comment by tylerforaie** [comment]
I think this is fixed in [2.54](https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v2.54.0).

I was unable to replicate the error with the above example in v2.59

**Comment by rossifumax** [comment]
Tested with latest version of AzureRM provider :
```
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0
```
and it's still not working : 
```
Error: creating/updating Application Gateway: Name "my-appgw" / Resource Group "my-rg-appgw"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ApplicationGatewayRewriteRuleSetActionSetInRewriteRuleCannotBeEmpty" Message="ActionSet is a required field in a RewriteRule." Details=[]
```
