### ISSUE TITLE
Error: ID was missing the `ioTApps` element - during terraform plan for existing IoT Central Application since 2.57.0 azurerm version

### ISSUE THREAD

**Issue by dariuszdbr** [terraform-providers/terraform-provider-azurerm#11678]
Upgrading my provider from `2.45.1` to the `2.58.0`, results with an error for my IoT Central Application during the terraform plan. I tried to upgrade step by step (from 2.45.1) and this error ("ID was missing the `ioTApps` element") started at the version 2.57.0.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

On my local machine:
Terraform v0.15.0
on windows_amd64
* provider.azurerm v2.57.0 & v2.58.0 

On ubuntu azure pipeline agent
Terraform v0.14.5
on linux_amd64
& 
Terraform v0.15.3
on linux_amd64
* provider.azurerm v2.57.0 & v2.58.0 

### Affected Resource(s)

* `azurerm_iotcentral_application`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.58.0" // starting from 2.45.1 (my current version) to 2.56.0 everything looks good
    }
  }
}

locals {
  location          = "westeurope"
  resourceprefix    = "iot-dd"
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "iotrg" {
    name = "${local.resourceprefix}-rg"
    location = "westeurope"
}

resource "azurerm_iotcentral_application" "iotmunicipalityica" {
  name                = "${local.resourceprefix}-ica-test-app"
  resource_group_name = azurerm_resource_group.iotrg.name
  location            = azurerm_resource_group.iotrg.location
  sub_domain          = "${local.resourceprefix}-ica-test-app"
  display_name        = "${local.resourceprefix}-ica-test-app"

  sku      = "ST1"
  template = "iotc-pnp-preview@1.0.0"

}

```
### Expected Behaviour

Displays: `No changes. Infrastructure is up-to-date.` on my plan.

### Actual Behaviour

Displays an error:
╷
│ Error: ID was missing the `ioTApps` element
│
│
╵

### Steps to Reproduce

1. Set the azurerm provider to whatever version from 2.45.1 to 2.56.0
2. `terraform init`
3. `terraform plan -out "test.tfplan"`
4. `terraform apply "test.tfplan"`
5. Change the azurerm provider version to 2.57.0 or 2.58.0 (currently the latest)
6. `terraform init -upgrade=true`
7. `terraform plan -out "test.tfplan"`

**Comment by njuCZ** [comment]
Hi @dariuszdbr thanks for pointing out this issue, I believe this issue is solved by #11641, new version will be released soon.

**Comment by dariuszdbr** [comment]
> Hi @dariuszdbr thanks for pointing out this issue, I believe this issue is solved by #11641, new version will be released soon.

@njuCZ I checked a minute ago, and the new version unfortunately did not solve the problem
I upgraded azurerm provider from version 2.56.0 to 2.59.0, and the result is the same, as described earlier.
