### ISSUE TITLE
2.66 crashes, not sure on which resource 

### ISSUE THREAD

**Issue by favoretti** [terraform-providers/terraform-provider-azurerm#12473]
```
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00145c8c0, 0x655b5c8, 0xc000b7ecc0, 0xc0043a2a80, 0x560bc60, 0xc000ff7c00, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00145c8c0, 0x655b5c8, 0xc000b7ecc0, 0xc00149a930, 0x560bc60, 0xc000ff7c00, 0xc0040aa678, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0014ee0a8, 0x655b5c8, 0xc000b7ecc0, 0xc000b7ed00, 0xc000b7ecc0, 0x40ba05, 0x591b140)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000b5e0e0, 0x655b670, 0xc000b7ecc0, 0xc0017237a0, 0xc000b5e0e0, 0xc003a5b140, 0xc001e77ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x5ad47c0, 0xc000b5e0e0, 0x655b670, 0xc003a5b140, 0xc001723740, 0x0, 0x655b670, 0xc003a5b140, 0xc003e40380, 0x374)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00013f6c0, 0x65a4dd8, 0xc000103080, 0xc003b0e000, 0xc0004a6510, 0x9a7ab30, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00013f6c0, 0x65a4dd8, 0xc000103080, 0xc003b0e000, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0011417a4, 0xc00013f6c0, 0x65a4dd8, 0xc000103080, 0xc003b0e000)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd
Error: The terraform-provider-azurerm_v2.66.0_x5 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by MasterKolka** [comment]
+1

Error: rpc error: code = Unavailable desc = transport is closing


panic: reflect: call of reflect.Value.IsNil on array Value
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: goroutine 1040 [running]:
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: reflect.Value.IsNil(...)
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 	/opt/goenv/versions/1.16.3/src/reflect/value.go:1086
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: github.com/mitchellh/mapstructure.(*Decoder).decodeSlice(0xc0017b11e8, 0x0, 0x0, 0x5513a40, 0xc002906830, 0x546ed40, 0xc00105dfb0, 0x197, 0xc0017b11e8, 0x8)
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/mitchellh/mapstructure/mapstructure.go:1086 +0x10ad
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: github.com/mitchellh/mapstructure.(*Decoder).decode(0xc0017b11e8, 0x0, 0x0, 0x5513a40, 0xc002906830, 0x546ed40, 0xc00105dfb0, 0x197, 0xc00105dfb0, 0x197)
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/mitchellh/mapstructure/mapstructure.go:460 +0x836
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: github.com/mitchellh/mapstructure.(*Decoder).Decode(0xc0017b11e8, 0x5513a40, 0xc002906830, 0x0, 0xc00105dfb0)
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/mitchellh/mapstructure/mapstructure.go:389 +0xf0
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: github.com/mitchellh/mapstructure.Decode(0x5513a40, 0xc002906830, 0x53e0020, 0xc00105dfb0, 0x1, 0xc000bf4b50)
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/mitchellh/mapstructure/mapstructure.go:297 +0xa5
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc00105dde8, 0xc0020affb0, 0x3, 0x3, 0x5513a40, 0xc002906830, 0xc00102a640, 0xc0029087f8, 0xffffffffffffffff)
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:127 +0xd2
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc00105dde8, 0xc0020affb0, 0x3, 0x3, 0x5513a40, 0xc002906830, 0x0, 0x0)
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:103 +0xde
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0xc00105dde8, 0xc001aecca0, 0x2, 0x2, 0x563cd60, 0xc0020afda0, 0xc00290a000, 0x10, 0x60122f0)
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:225 +0x21a
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc00105dde8, 0xc001aecca0, 0x2, 0x2, 0x563cd60, 0xc0020afda0, 0x4, 0xaf9559)
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:109 +0x1de
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:123
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0xc00105dde8, 0xc0029068f0, 0x1, 0x1, 0x546ed40, 0xc00105df38, 0xc00102b7c0, 0x5e04135, 0xc001aef900)
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:143 +0x29e
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc00105dde8, 0xc0029068f0, 0x1, 0x1, 0x546ed40, 0xc00105df38, 0x1, 0x1)
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_writer_map.go:103 +0xde
2021-07-05T08:00:58.711Z [DEBUG] plugin.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).WriteField(0xc00105dde8, 0xc0029068f0, 0x1, 0x1, 0x546ed40, 0xc00105df38, 0x0, 0x0)

**Comment by dmatton** [comment]
Hello,

Same crash for me with v2.66. If I use the previous version (v2.65), everything works perfectly.

This is the message

```bash
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: PANIC: runtime error: invalid memory address or nil pointer dereference
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b804ea]
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5:
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: goroutine 1740 [running]:
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/recoveryservices.resourceSiteRecoveryReplicatedItemRead(0xc002958300, 0x620a540, 0xc001221500, 0x0, 0x0)
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/recoveryservices/site_recovery_replicated_vm_resource.go:465 +0xb6a
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000efaa80, 0x715ab68, 0xc0016ea1c0, 0xc002958300, 0x620a540, 0xc001221500, 0x0, 0x0, 0x0)
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000efaa80, 0x715ab68, 0xc0016ea1c0, 0xc0010941c0, 0x620a540, 0xc001221500, 0xc000866358, 0x0, 0x0, 0x0)
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00135a738, 0x715ab68, 0xc0016ea1c0, 0xc0016ea200, 0xc0016ea1c0, 0x100b705, 0x6519e00)
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0013af3a0, 0x715ac10, 0xc0016ea1c0, 0xc001516300, 0xc0013af3a0, 0xc003298720, 0xc002745ba0)
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x66d3400, 0xc0013af3a0, 0x715ac10, 0xc003298720, 0xc0015162a0, 0x0, 0x715ac10, 0xc003298720, 0xc00254c400, 0xb16)
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fe8c0, 0x71a4538, 0xc000602900, 0xc002496000, 0xc000b0a2d0, 0xa67dcd0, 0x0, 0x0, 0x0)
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc0001fe8c0, 0x71a4538, 0xc000602900, 0xc002496000, 0x0)
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000b172c0, 0xc0001fe8c0, 0x71a4538, 0xc000602900, 0xc002496000)
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-07-05T16:47:22.532+0200 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd
2021-07-05T16:47:22.538+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-07-05T16:47:22.538+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-07-05T16:47:22.538+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-07-05T16:47:22.538+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-07-05T16:47:22.538+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-07-05T16:47:22.538+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-07-05T16:47:22.538+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-07-05T16:47:22.538+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-07-05T16:47:22.538+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-07-05T16:47:22.538+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-07-05T16:47:22.539+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-07-05T16:47:22.539+0200 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azurerm/2.66.0/darwin_amd64/terraform-provider-azurerm_v2.66.0_x5 pid=14826 error="exit status 2"
2021-07-05T16:47:22.539+0200 [ERROR] plugin.(*GRPCProvider).UpgradeResourceState: error="rpc error: code = Canceled desc = context canceled"
2021-07-05T16:47:22.540+0200 [INFO]  backend/local: plan operation completed
╷
│ Error: Plugin did not respond
│
│   with azurerm_site_recovery_replicated_vm.vm-replication-vm-ecom-002,
│   on 05-backups.tf line 154, in resource "azurerm_site_recovery_replicated_vm" "vm-replication-vm-ecom-002":
│  154: resource "azurerm_site_recovery_replicated_vm" "vm-replication-vm-ecom-002" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_linux_virtual_machine_scale_set.scalesetlinuxsharenfs01,
│   on 10-deployshareVm.tf line 73, in resource "azurerm_linux_virtual_machine_scale_set" "scalesetlinuxsharenfs01":
│   73: resource "azurerm_linux_virtual_machine_scale_set" "scalesetlinuxsharenfs01" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_monitor_autoscale_setting.autoscalefrontend01,
│   on 20-frontend.tf line 311, in resource "azurerm_monitor_autoscale_setting" "autoscalefrontend01":
│  311: resource "azurerm_monitor_autoscale_setting" "autoscalefrontend01" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_monitor_autoscale_setting.autoscalefrontend02,
│   on 20-frontend.tf line 459, in resource "azurerm_monitor_autoscale_setting" "autoscalefrontend02":
│  459: resource "azurerm_monitor_autoscale_setting" "autoscalefrontend02" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_monitor_autoscale_setting.autoscalebackend01,
│   on 30-backend.tf line 139, in resource "azurerm_monitor_autoscale_setting" "autoscalebackend01":
│  139: resource "azurerm_monitor_autoscale_setting" "autoscalebackend01" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_virtual_machine_scale_set_extension.health_agent,
│   on 30-backend.tf line 196, in resource "azurerm_virtual_machine_scale_set_extension" "health_agent":
│  196: resource "azurerm_virtual_machine_scale_set_extension" "health_agent" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│
│   with azurerm_monitor_autoscale_setting.autoscalebackend02,
│   on 30-backend.tf line 268, in resource "azurerm_monitor_autoscale_setting" "autoscalebackend02":
│  268: resource "azurerm_monitor_autoscale_setting" "autoscalebackend02" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_virtual_machine_scale_set_extension.health_agent02,
│   on 30-backend.tf line 325, in resource "azurerm_virtual_machine_scale_set_extension" "health_agent02":
│  325: resource "azurerm_virtual_machine_scale_set_extension" "health_agent02" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_linux_virtual_machine_scale_set.scalesetlinuxstaging01[0],
│   on 50-staging.tf line 86, in resource "azurerm_linux_virtual_machine_scale_set" "scalesetlinuxstaging01":
│   86: resource "azurerm_linux_virtual_machine_scale_set" "scalesetlinuxstaging01" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_mssql_server.sqlserver01,
│   on 60-sql-server.tf line 21, in resource "azurerm_mssql_server" "sqlserver01":
│   21: resource "azurerm_mssql_server" "sqlserver01" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_mssql_server.sqlserver51,
│   on 60-sql-server.tf line 117, in resource "azurerm_mssql_server" "sqlserver51":
│  117: resource "azurerm_mssql_server" "sqlserver51" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.66.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b804ea]

goroutine 1740 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/recoveryservices.resourceSiteRecoveryReplicatedItemRead(0xc002958300, 0x620a540, 0xc001221500, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/recoveryservices/site_recovery_replicated_vm_resource.go:465 +0xb6a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000efaa80, 0x715ab68, 0xc0016ea1c0, 0xc002958300, 0x620a540, 0xc001221500, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000efaa80, 0x715ab68, 0xc0016ea1c0, 0xc0010941c0, 0x620a540, 0xc001221500, 0xc000866358, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00135a738, 0x715ab68, 0xc0016ea1c0, 0xc0016ea200, 0xc0016ea1c0, 0x100b705, 0x6519e00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0013af3a0, 0x715ac10, 0xc0016ea1c0, 0xc001516300, 0xc0013af3a0, 0xc003298720, 0xc002745ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x66d3400, 0xc0013af3a0, 0x715ac10, 0xc003298720, 0xc0015162a0, 0x0, 0x715ac10, 0xc003298720, 0xc00254c400, 0xb16)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fe8c0, 0x71a4538, 0xc000602900, 0xc002496000, 0xc000b0a2d0, 0xa67dcd0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001fe8c0, 0x71a4538, 0xc000602900, 0xc002496000, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000b172c0, 0xc0001fe8c0, 0x71a4538, 0xc000602900, 0xc002496000)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.66.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2021-07-05T16:47:22.699+0200 [DEBUG] provider: plugin exited
```

**Comment by aristosvo** [comment]
The problem is probably in the new terraform-plugin-sdk version used in 2.66.0. I reported it to the HC maintainers for the Azure provider, hope to hear more today.

**Comment by jmyers82** [comment]
For those needing a fix, assuming you are on a version of terraform using the .terraform.lock.hcl:

remove the hashes section below and set the version to 2.65.0 and delete the .terraform folder and re run terraform init and it will repopulate the hash for you and get the 2.65.0 version which is working fine. 

provider "registry.terraform.io/hashicorp/azurerm" {
  version = "2.65.0"
  hashes = [
    "h1:3jSw0J5yIjQfdwphFtOZylM1viYfWlVPp5E2URHb2HQ=",
    "zh:03ffb2151a9d8d6f3e7a5a1985cfecdb30b91781577b83be8fa75d050f75b2d8",
    "zh:3631760913bc9e4727de34cc5d54eb92661ced73b75fc50c21dd2af2aa0c71f2",
    "zh:36bee282d96334ecf8cd468dbd49ef56afbd9634db1b84f5df54f926ee17ce88",
    "zh:53e986e3458bf38013194147e44f067979f99d480436a2b845a3a1190fa9d05f",
    "zh:560595d18566666d1ae2cc9da0e0a321d549c9caa716f29ee670025ce6c5cb2a",
    "zh:8d6709d19211325ebc78f474741623c4c7c28407d109f3740ab008379a8e0f40",
    "zh:bf7f949faca42744048e85f6fa4fa72eb4815ef2e0bcca60dba7f5afbbc8f589",
    "zh:cd09a82e23656c9a1b0314b2480993f2cce21325ce2a595f434614f0ac5adc6b",
    "zh:d1b60c0d729e1a9e676e4962beaad5fc0f4c12e748cf1d8dcd2f4df6273dd3d1",
    "zh:e477221421a97a0f5e8111508b6d57469bd6d5cf2cc374ed08d31f7bbbdaaf20",
    "zh:f00f71f4a2514bcb49135b66a7bb3c0bb52c032a438277dc56606be36724b8bd",
  ]
}

**Comment by jackofallops** [comment]
Thanks for reporting - there are 2 crashes in the traces that I can see, one is fixed in #12476 as mentioned by @aristosvo, but it appears there's another (unrelated) crash in `azurerm_site_recovery_replicated_vm` as a result of the new property introduced in #12374, I'll PR a fix as soon as I've tested it. The original trace is incomplete, so I can't tell if there's another problem in there. @favoretti - Can you provide the full trace here?

**Comment by favoretti** [comment]
@jackofallops I'm not sure it's the fix. I don't use the resource you patched and 2.66 still crashed for me.

**Comment by favoretti** [comment]
Oh, I'm sorry, missed your comment. Will run a trace today.

**Comment by jackofallops** [comment]
> Oh, I'm sorry, missed your comment. Will run a trace today.

thanks @favoretti - I don't need a `TF_LOG=trace` just the full stack trace from the panic itself to let me see where it bailed. 👍
