### ISSUE TITLE
Unable to create storage account

### ISSUE THREAD

**Issue by landro** [terraform-providers/terraform-provider-azurerm#1833]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Azure Provider version: 1.13.0

### Affected Resource(s)

* azurerm_storage_account

### Terraform Configuration Files

```hcl

provider "azurerm" {
  version = "1.13.0"
}

resource "azurerm_storage_account" "production" {
  name = "productionsignering"
  resource_group_name = "${azurerm_resource_group.production.name}"

  location = "${azurerm_resource_group.production.location}"

  account_kind = "BlobStorage"
  account_tier = "Standard"

  account_replication_type = "LRS" // RAGRS
  access_tier = "Hot"

  enable_blob_encryption = true
  enable_https_traffic_only = true
  account_encryption_source = "Microsoft.Storage"

  network_rules {
    virtual_network_subnet_ids = ["${azurerm_subnet.kubernetes.id}"]
  }

}
```

### Debug Output

```
azurerm_storage_account.production: Still creating... (10s elapsed)
...
azurerm_storage_account.production: Still creating... (3m40s elapsed)
2018-08-27T14:48:18.329+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: 2018/08/27 14:48:18 [DEBUG] AzureRM Request:
2018-08-27T14:48:18.329+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: GET /subscriptions/UUID/providers/Microsoft.Storage/locations/westeurope/asyncoperations/UUID?monitor=true&api-version=2017-10-01 HTTP/1.1
2018-08-27T14:48:18.329+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: Host: management.azure.com
2018-08-27T14:48:18.329+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: User-Agent: Go/go1.10.3 (amd64-darwin) go-autorest/v10.12.0 Azure-SDK-For-Go/v18.0.0 storage/2017-10-01;HashiCorp-Terraform-v0.11.3
2018-08-27T14:48:18.329+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: Authorization: Bearer asdfsadfasdfasdf
2018-08-27T14:48:18.329+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: Accept-Encoding: gzip
2018-08-27T14:48:18.329+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4:
2018-08-27T14:48:18.329+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4:
2018-08-27T14:48:18.622+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: 2018/08/27 14:48:18 [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/uuid/providers/Microsoft.Storage/locations/westeurope/asyncoperations/uuid?monitor=true&api-version=2017-10-01:
2018-08-27T14:48:18.622+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: HTTP/1.1 400 Bad Request
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: Content-Length: 523
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: Cache-Control: no-cache
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: Content-Type: application/json
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: Date: Mon, 27 Aug 2018 12:48:17 GMT
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: Expires: -1
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: Pragma: no-cache
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: Server: Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: Strict-Transport-Security: max-age=31536000; includeSubDomains
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: X-Content-Type-Options: nosniff
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: X-Ms-Correlation-Request-Id: uuid
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: X-Ms-Ratelimit-Remaining-Subscription-Reads: 11991
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: X-Ms-Request-Id: 24a57e7a-4ac3-4397-873e-f28a16d02134
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4: X-Ms-Routing-Request-Id: WESTEUROPE:20180827T124818Z:uuid
2018-08-27T14:48:18.623+0200 [DEBUG] plugin.terraform-provider-azurerm_v1.13.0_x4:
2018/08/27 14:48:18 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* azurerm_storage_account.production: Error waiting for Azure Storage Account "productionsignering" to be created: pollingTrackerPut#checkForErrors: the response did not contain a body: StatusCode=0
2018/08/27 14:48:18 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
```

### Expected Behavior

Storage account should have been created

### Actual Behavior

Storage account was not created. 
To me, this looks like an issue with the API binding and possibly even with the API endpoint. First of all,  
GET /subscriptions/UUID/providers/Microsoft.Storage/locations/westeurope/asyncoperations/UUID?monitor=true&api-version=2017-10-01 should not return a 400 bad request. In addition, the response returned does not contain a response body even if the Content-Length response header indicates otherwise.
 
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Tried this in both North Europe and West Europe with same result.

**Comment by jeffreyCline** [comment]
@landro I am unable to repro this issue, can you confirm this is still happening?

**Comment by tombuildsstuff** [comment]
I may be wrong, but I have a feeling this may have been fixed by upgrading [to v10.15.4 of `github.com/Azure/go-autorest`](https://github.com/terraform-providers/terraform-provider-azurerm/pull/1909) which was merged yesterday and will go out in the next release?

**Comment by landro** [comment]
Upgraded to 1.14.0 - still getting the same result. Will try to build the plugin from master to see if that works better.

**Comment by landro** [comment]
Tested with master. Works as expected. Thanks!

**Comment by tombuildsstuff** [comment]
@landro great thanks for confirming - that'll ship as a part of v1.15 soon ™️ :)
