### ISSUE TITLE
Terraform AuthorizationFailed on (unused) provider Microsoft.Media

### ISSUE THREAD

**Issue by msuringa** [terraform-providers/terraform-provider-azurerm#3358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
provider.azurerm v1.27.0

### Affected Resource(s)

all

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=1.27.0"
  tenant_id = "...."
  subscription_id = "..."
  client_id = "..."
  client_secret = "..."
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Terraform should authenticate with Azure and register the providers that it requires

### Actual Behavior

Terraform fails with the below error message

* provider.azurerm: Error ensuring Resource Providers are registered: Cannot register provider Microsoft.Media with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '.........' with object id '............' does not have authorization to perform action 'Microsoft.Media/register/action' over scope '/subscriptions/........'.".

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I am running this terraform module with a service principal that has limited access inside the Azure subscription. In this case it only has access to manage storage accounts and related resources, but it does not have access to any Media resources. It appears that terraform attempts to do a basic init which requires access to this, so it fails. I have had to revert my version back to 1.22.0 because that version does not yet include media (and stream analytics, which it also fails on) resources. Since I won't be managing these resources with this service principal, I don't need access to them.

**Comment by tombuildsstuff** [comment]
hi @msuringa 

Thanks for opening this issue :)

This bug was [fixed in v1.27.1 of the Provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1271-april-26-2019) - would you able to try upgrading and see if that works for you? In addition, whilst Terraform will attempt to automatically register any Resource Providers we support - you can configure Terraform not to register any Resource Providers [using the `skip_provider_registration` flag](https://www.terraform.io/docs/providers/azurerm/index.html#skip_provider_registration).

Since the underlying bug has been fixed I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by msuringa** [comment]
Hi @tombuildsstuff 

Thank you for the quick reply. I actually noticed the same issue occurring in version 1.27.1, but then with the Microsoft.StreamAnalytics or Microsoft.DevSpaces provider instead of the Microsoft.Media provider, but I wasn't aware of the flag you mentioned. With the property set, it works as expected.

Thanks!

**Comment by firestonem** [comment]
Hey @tomasaschan 

This issue should be reopened as a bug. My provider version is v1.27.1:
```
$ ls .terraform/plugins/darwin_amd64/
lock.json*                             terraform-provider-azurerm_v1.27.1_x4*
```

but it still throws the error message:

> * provider.azurerm: Error ensuring Resource Providers are registered: Cannot register provider Microsoft.Media with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxx-xxx-xxx' with object id 'xxx-xxx-xxx' does not have authorization to perform action 'Microsoft.Media/register/action' over scope '/subscriptions/xxx-xxx-xxx'.".

It can be ignored by skipping registration as suggested above, but the underlying issue is still present.

**Comment by tombuildsstuff** [comment]
@firestonem 

> This issue should be reopened as a bug. My provider version is v1.27.1:
> It can be ignored by skipping registration as suggested above, but the underlying issue is still present.

Terraform's list of Required Resource Providers is additive and has grown over time to support all of the Resource Providers for which Terraform has Resources - and as such to Terraform attempts to register any Resource Providers which it supports.

Whilst it's possible to disable this behaviour (as you've mentioned, by using the flag/environment variable) - this is an advanced scenario intended for use where the Resource Provider registration needs to be managed externally to Terraform.

Given the Client being used doesn't have permissions to register the `Microsoft.Media` Resource Provider, it appears this functionality is working as intended (by raising an error) and that you'll need to use the flag/environment variable to disable the automatic Resource Provider Registration (since the Client doesn't have permission) which means this'll be skipped

Thanks!
