### ISSUE TITLE
Error reading the advanced threat protection settings of AzureRM Storage Account

### ISSUE THREAD

**Issue by enorlando** [terraform-providers/terraform-provider-azurerm#3968]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform v0.11.14
azurerm v1.32.0

### Affected Resource(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "xxx" {
  name                     = "xxx"
  resource_group_name      = "${azurerm_resource_group.xxx.name}"
  location                 = "${var.location}"
  account_tier             = "Standard"
  account_replication_type = "RAGRS"
}
```

### Debug Output
* Logging onto the azure portal and checking the storage account in question does not have ```Advanced Threat Protection``` enabled.
* Running az login I am able to auth and access all subscriptions
* Reverting the provider back to 1.31.0 has no issue

### Expected Behavior

Run a terraform plan with no changes
```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### Actual Behavior

```
Error: Error refreshing state: 1 error occurred:
        * azurerm_storage_account.xxx: 1 error occurred:
        * azurerm_storage_account.xxx: azurerm_storage_account.xxx: Error reading the advanced threat protection settings of AzureRM Storage Account "xxx": security.AdvancedThreatProtectionClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription 'xxx' could not be found."
```

### Steps to Reproduce

1. `terraform plan`

**Comment by katbyte** [comment]
Hi @enorlando,

This has been fixed in an upcoming hotfix release (v1.32.1) that with luck should go out today/tomorrow. As such I am going to close it.

**Comment by enorlando** [comment]
Hi @katbyte,
I have updated the provider to the hotfix mentioned v1.32.1 and still have the same issue

**Comment by enorlando** [comment]
Hi @katbyte,
We updated our provider to v1.32.1 but we are still getting the same error.

**Comment by guri-s** [comment]
Issue was with the storage account in question. Can confirm it's sorted now.
