### ISSUE TITLE
Can't create premium storage share

### ISSUE THREAD

**Issue by rukawata** [terraform-providers/terraform-provider-azurerm#4350]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_storage_share`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "nancyc-as-4"
  location = "westus2"
}

resource "azurerm_storage_account" "test" {
  name                     = "nancycas4"
  resource_group_name      = "${azurerm_resource_group.test.name}"
  location                 = "${azurerm_resource_group.test.location}"
  account_tier             = "Premium"
  account_replication_type = "LRS"
}

resource "azurerm_storage_share" "testshare" {
  name                 = "nancycashare4"
  storage_account_name = "${azurerm_storage_account.test.name}"
  quota                = 5120
}

```

### Debug Output
[201909171610.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/3623738/201909171610.log)

### Expected Behavior

Create a storage share with premium azure file.
The configuration works if `account_tier = "Standard"`

### Actual Behavior

It failed with error:

Error: Error creating Share "nancycashare4" (Account "nancycas4" / Resource Group "nancyc-as-4"): shares.Client#Create: Failure sending request: StatusCode=0 -- Original Error: Put https://nancycas4.file.core.windows.net/nancycashare4?restype=share: dial tcp: lookup nancycas4.file.core.windows.net: no such host

  on main.tf line 14, in resource "azurerm_storage_share" "testshare":
  14: resource "azurerm_storage_share" "testshare" {

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @rukawata 

Thanks for opening this issue.

Taking a look into this it appears this has been fixed via #4235, which will be released as a part of v1.34 later today (@hashibot will comment on this issue when that's done) - as such I'm going to close this issue for the moment, however should you need to work around this in the interim you should be able to use version `1.32.0` of the Azure Provider for the moment.

Thanks!

**Comment by rukawata** [comment]
Hi @tombuildsstuff,

Thanks for looking into this. I just tested with 1.34 and still faces the same issue.
[201909181311.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/3628211/201909181311.log)

Thanks,
Nancy
