### ISSUE TITLE
Storage Account Error 504 GatewayTimeout

### ISSUE THREAD

**Issue by ranokarno** [terraform-providers/terraform-provider-azurerm#4480]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.11.11
AzureRm v1.34.0

### Affected Resource(s)

* `azurerm_storage_account`

### Debug Output

```
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: [DEBUG] AzureRM Response for https://management.azure.com/%2Fsubscriptions%xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%2FresourceGroups%2Fresource-group%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fstorage_account_name1/providers/Microsoft.Security/advancedThreatProtectionSettings/current?api-version=2017-08-01-preview:
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: HTTP/2.0 504 Gateway Timeout
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: Content-Length: 146
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: Cache-Control: no-cache
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: Content-Type: application/json; charset=utf-8
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: Date: Wed, 02 Oct 2019 06:17:20 GMT
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: Expires: -1
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: Pragma: no-cache
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: Strict-Transport-Security: max-age=31536000; includeSubDomains
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: X-Content-Type-Options: nosniff
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: X-Ms-Correlation-Request-Id: 08903a37-7682-57e7-7a93-8124f51a6a3f
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: X-Ms-Failure-Cause: service
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: X-Ms-Request-Id: 21d70332-ca3b-4857-a26b-6484280d4ec6
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: X-Ms-Routing-Request-Id: EASTASIA:20191002T061720Z:21d70332-ca3b-4857-a26b-6484280d4ec6
2019-10-02T06:17:20.958Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: 
2019-10-02T06:17:50.959Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: [DEBUG] AzureRM Request:
2019-10-02T06:17:50.959Z [DEBUG] plugin.terraform-provider-azurerm_v1.34.0_x4: GET /%2Fsubscriptions%xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%2FresourceGroups%2Fresource-group%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fstorage_account_name1/providers/Microsoft.Security/advancedThreatProtectionSettings/current?api-version=2017-08-01-preview HTTP/1.1
```

### Expected Behavior

below command should be working
terraform plan
terraform apply

### Actual Behavior

```hcl
* azurerm_storage_account.instance: Error reading the advanced threat protection settings of AzureRM Storage Account "storage_account_name": security.AdvancedThreatProtectionClient#Get: Failure responding to request: StatusCode=504 -- Original Error: autorest/azure: Service returned an error. Status=504 Code="GatewayTimeout" Message="The gateway did not receive a response from 'Microsoft.Security' within the specified time period."
```

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### References

* #3968

**Comment by matthieuklotz** [comment]
Same issue with terraform 0.12.9

**Comment by c054864** [comment]
Interesting, I too have experienced this problem over the last two days and put it down to Azure / service issue.  Yesterday, the problem went a way around 11:00BST, but I have it again this morning.

**Comment by tombuildsstuff** [comment]
hi @ranokarno @matthieuklotz 

Thanks for opening this issue.

Unfortunately this is an issue within the Azure API where the Internal API isn't responding to the Public Azure API within a designated time period - as such unfortunately there's not a lot we can do to work around this. As @c054864 has mentioned this appears to be intermittent - as such I'm going to suggest opening an issue with Microsoft Support (which we'll do on our side too) - but for the moment I'm going to close this issue since this is an issue with the Azure API, rather than something specific to Terraform.

Thanks!

**Comment by kheiakiyama** [comment]
Sometimes same problem has occurred in my environment since yesterday.

**Comment by ranokarno** [comment]
@kheiakiyama , as mentioned by @tombuildsstuff 
issue is still ongoing and spreading worldwide due to backend Azure API. You may need to open support ticket.

**Comment by c054864** [comment]
Hi @ranokarno  / @kheiakiyama , this is the 3rd day in the row I've had this issue, and it typically clears up around 11:30BST for me.  I've raised a support case, albeit based on a developers account so no clout but Azure have responded stating its a know backend problem and is being worked on.

**Comment by kheiakiyama** [comment]
@c054864 Thank you for your sharing.
I will also raise a support case in order to hurry up.

**Comment by matthieuklotz** [comment]
Hi everyone,

I have raised a support case yesterday and they have confirm the issue. The support have just mail me that everything should work fine now.

**Comment by kheiakiyama** [comment]
I also hear a bug is fixed from support.

**Comment by tombuildsstuff** [comment]
@kheiakiyama @matthieuklotz glad to hear this is now working for you 👍

**Comment by ranokarno** [comment]
hi @tombuildsstuff ,

I heard from Microsoft that this issue is not fully resolved. MS said it is pending Terraform to change ATP API url to stable version.
```
GET /%2Fsubscriptions%2F<subscription_id>2b%2FresourceGroups%2Fexample-resources%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2F<storage_account_name>/providers/Microsoft.Security/advancedThreatProtectionSettings/current?api-version=2017-08-01-preview HTTP/1.1
```
