### ISSUE TITLE
Example usage in the documentation is out-of-date for azurerm_container_group

### ISSUE THREAD

**Issue by JunyiYi** [terraform-providers/terraform-provider-azurerm#506]
### Terraform Version
Terraform v0.10.9-dev
Provider.AzureRM v0.3.2

### Affected Resource(s)
- azurerm_container_group ([Documentation](https://www.terraform.io/docs/providers/azurerm/r/container_group.html))

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "aci-rg" {
  name     = "aci-test"
  location = "west us"
}

resource "azurerm_storage_account" "aci-sa" {
  name                = "acistorageacct"
  resource_group_name = "${azurerm_resource_group.aci-rg.name}"
  location            = "${azurerm_resource_group.aci-rg.location}"
  account_type        = "Standard_LRS"
}

resource "azurerm_storage_share" "aci-share" {
  name = "aci-test-share"

  resource_group_name  = "${azurerm_resource_group.aci-rg.name}"
  storage_account_name = "${azurerm_storage_account.aci-sa.name}"

  quota = 50
}

resource "azurerm_container_group" "aci-helloworld" {
  name                = "aci-hw"
  location            = "${azurerm_resource_group.aci-rg.location}"
  resource_group_name = "${azurerm_resource_group.aci-rg.name}"
  ip_address_type     = "public"
  os_type             = "linux"

  container {
    name = "hw"
    image = "seanmckenna/aci-hellofiles"
    cpu ="0.5"
    memory =  "1.5"
    port = "80"

    environment_variables {
        "NODE_ENV"="testing"
    }

    command = "/bin/bash -c '/path to/myscript.sh'"

    volume {
      name = "logs"
      mount_path = "/aci/logs"
      read_only = false
      share_name = "${azurerm_storage_share.aci-share.name}"
      storage_account_name = "${azurerm_storage_account.aci-sa.name}"
      storage_account_key = "${azurerm_storage_account.aci-sa.primary_access_key}"
    }
  }

  container {
    name   = "sidecar"
    image  = "microsoft/aci-tutorial-sidecar"
    cpu    = "0.5"
    memory = "1.5"
  }

  tags {
    environment = "testing"
  }
}
```

### Expected Behavior
Successfully provision the container group by copy-pasting the example code from the [documentation](https://www.terraform.io/docs/providers/azurerm/r/container_group.html).

### Actual Behavior
- **Warnings:** azurerm_storage_account.aci-sa: "account_type": [DEPRECATED] This field has been split into `account_tier` and `account_replication_type`
- **Error:** azurerm_storage_account.aci-sa: "account_replication_type": required field is not set
- **Error:** azurerm_storage_account.aci-sa: "account_tier": required field is not set

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

**Comment by mocofound** [comment]
Code to reflect the move from account_type to account_tier and account_replication_type within azurerm_storage_account in the azurerm_container_group documentation/example code is included in 
PR #556

**Comment by mocofound** [comment]
PR #556 was merged yesterday.

**Comment by tombuildsstuff** [comment]
Closing as this has been fixed via #556

**Comment by tsellers-r7** [comment]
@tombuildsstuff - The documentation  ( https://www.terraform.io/docs/providers/azurerm/r/container_group.html ) referenced in this issue still contains the out of date information.  Is this information source rebuilt periodically or should there be additional changes? 
Thank.

**Comment by tombuildsstuff** [comment]
@tsellers-r7 apologies, I'd meant to cherry-pick the website changes across into the `stable-website` branch but had forgotten to do so) - meaning this is still out of date. We'll be doing a release later today when this'll get updated on the website; sorry for the delay / confusion here!
