### ISSUE TITLE
Example usage (Import PFX) in the documentation doesn't work for azurerm_key_vault_certificate

### ISSUE THREAD

**Issue by JunyiYi** [terraform-providers/terraform-provider-azurerm#520]
### Terraform Version
Terraform v0.10.9-dev
Provider.AzureRM: v0.3.2

### Affected Resource(s)
- azurerm_key_vault_certificate ([Documentation](https://www.terraform.io/docs/providers/azurerm/r/key_vault_certificate.html))

### Terraform Configuration Files
```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "test" {
  name     = "key-vault-certificate-example"
  location = "West Europe"
}

resource "azurerm_key_vault" "test" {
  name                = "keyvaultcertexample"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  tenant_id           = "${data.azurerm_client_config.current.tenant_id}"

  sku {
    name = "standard"
  }

  access_policy {
    tenant_id = "${data.azurerm_client_config.current.tenant_id}"
    object_id = "${data.azurerm_client_config.current.service_principal_object_id}"

    certificate_permissions = [
      "all",
    ]

    key_permissions = [
      "all",
    ]

    secret_permissions = [
      "all",
    ]
  }

  tags {
    environment = "Production"
  }
}


resource "azurerm_key_vault_certificate" "test" {
  name      = "imported-cert"
  vault_uri = "${azurerm_key_vault.test.vault_uri}"

  certificate {
    contents = "${base64encode(file("certificate-to-import.pfx"))}"
    password = ""
  }

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = false
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }
  }
}
```

### Expected Behavior
Terraform should be able to calculate the resources to be created.

### Actual Behavior
- **Error:** azurerm_key_vault.test: expected access_policy.0.certificate_permissions.0 to be one of [create delete deleteissuers get getissuers import list listissuers managecontacts manageissuers setissuers update], got all
- **Error:** azurerm_key_vault.test: expected access_policy.0.key_permissions.0 to be one of [backup create decrypt delete encrypt get import list purge recover restore sign unwrapKey update verify wrapKey], got all
- **Error:** azurerm_key_vault.test: expected access_policy.0.secret_permissions.0 to be one of [backup delete get list purge recover restore set], got all

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Export a certificate with private key to "./certificate-to-import.pfx" 
2. Copy the *Example Usage (Importing a PFX)* from the [documentation](https://www.terraform.io/docs/providers/azurerm/r/key_vault_certificate.html) to "./main.tf"
3. `terraform init`
4. `terraform plan`

**Comment by tombuildsstuff** [comment]
From what I can tell this has been fixed via #522 - closing

**Comment by Moeser** [comment]
This is still an issue for the second example on the same page (new certificates).
