### ISSUE TITLE
Private Link Endpoint resource doesn't accept DNS Alias

### ISSUE THREAD

**Issue by techbunny** [terraform-providers/terraform-provider-azurerm#5556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
v0.12.20

### Affected Resource(s)

* `azurerm_private_endpoint`

### Terraform Configuration Files

```hcl
resource "azurerm_private_endpoint" "example" {
  name                = "ExampleName"
  location            = var.location
  resource_group_name = local.resource_group_name
  subnet_id           = azurerm_subnet.subnetname.id

  private_service_connection {
    name                              = "ToEndpoint"
    is_manual_connection              = true
    private_connection_resource_id      = "uniquednsname.eastus.azure.privatelinkservice"
    request_message                   = "Customer # XXXX"

  }
}
```
### Expected Behavior

Azure supports either the resource ID or the DNS name to reference the private link service. I expected to be able to provide the DNS FQDN as the "private_connection_resource_id" or have an option to pass a "private_connection_alias" or similar.

### Actual Behavior

Terraform returned an error that it was an invalid URI for the request.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by cashman04** [comment]
Same issue/same terraform version.

    resource "azurerm_private_endpoint" "prod-snowflake" {
      name                = "pve-eastus2-prod-snowflake-0"
      location            = "eastus2"
      resource_group_name = azurerm_resource_group.prodinfra.name
      subnet_id           = azurerm_subnet.prod-snowflake.id

      private_service_connection {
        name = "psc-eastus2-prod-snowflake-0"
        is_manual_connection = true
        private_connection_resource_id = "sf-pvlinksvc-azeastus2.cf82bce2-be9d-4dc6-92ee-3de5fb04d191.eastus2.azure.privatelinkservice"  
      }
    }

Error message:

    Error: Can not parse "private_service_connection.0.private_connection_resource_id" as a resource id: Cannot parse Azure ID: parse sf-pvlinksvc-azeastus2.cf82bce2-be9d-4dc6-92ee-3de5fb04d191.eastus2.azure.privatelinkservice: invalid URI for request

**Comment by WodansSon** [comment]
@techbunny thank you for opening this issue, the version of the API we are currently using (`2019-09-01`) does not support using an `alias` or the `DNS FQDN` as the `private_connection_resource_id`, so unfortunately this will have to wait until we upgrade to the `2019-11-01` version of the API which will be pretty much a total rewrite of the resource as the API has changed so much between the versions, but we will cross that bridge when we get there.

**Comment by stazz** [comment]
Hi @WodansSon ,

Any news about updating the PE API to `2019-11-01` (or newer?)? I see there are couple of issues about the need to update the API, this included. We are currently hitting this one, as we try to create PE to Snowflake DB. Is there already some work started on this in some branch or something? :)

**Comment by Radamonas** [comment]
Any news about this issue?

**Comment by PengJLi** [comment]
Any update on this issue? Snowflake PE blocked by this as well.

**Comment by themaxz-vt** [comment]
Hello. I am experincing the same issue while trying to set up a private link to snowflake using terraform. 
Any update regarding the api update?

**Comment by Marcus-James-Adams** [comment]
Is it just snowflake users who are seeing this issue? (myself included)
Is there an ETA for the API upgrade?

**Comment by markkeig** [comment]
Any ETA would be appreciated!

**Comment by adrianmo** [comment]
As a workaround until this is natively supported, you can use the generic [`azurerm_resource_group_template_deployment`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group_template_deployment) resource to create the Private Endpoint with a DNS alias connection. 

I've given it a try below, but I haven't actually tested it, so it might require some tweaks. 

```terraform
resource "azurerm_resource_group_template_deployment" "private_endpoint" {
  name                = "ExampleName"
  resource_group_name = azurerm_resource_group.example.name
  deployment_mode     = "Incremental"
  parameters_content  = jsonencode({
    "privateEndpointName": "ExampleName",
    "subnetId": azurerm_subnet.subnetname.id,
    "alias": "uniquednsname.eastus.azure.privatelinkservice",
    "requestMessage": "Customer # XXXX"
  })
  template_content    = <<TEMPLATE
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "privateEndpointName": {
      "type": "string",
      "metadata": {
        "description": "Name of the Private Endpoint"
      }
    },
    "subnetId": {
      "type": "string",
      "metadata": {
        "description": "The subnet to deploy and allocate private IP addresses from a virtual network"
      }
    },
    "alias": {
      "type": "string",
      "metadata": {
        "description": "Private link resource DNS alias"
      }
    },
    "requestMessage": {
      "type": "string",
      "metadata": {
        "description": "Private connection request message"
      }
    }
  },
  "resources": [
    {
      "type": "Microsoft.Network/privateEndpoints",
      "apiVersion": "2020-06-01",
      "name": "[parameters('privateEndpointName')]",
      "location": "[resourceGroup().location]",
      "properties": {
        "subnet": {
          "id": "[parameters('subnetId')]"
        },
        "privateLinkServiceConnections": [
          {
            "name": "[parameters('privateEndpointName')]",
            "properties": {
              "privateLinkServiceId": "[parameters('alias')]",
              "requestMessage": "[parameters('requestMessage')]"
            }
          }
        ]
      }
    }
  ]
}
TEMPLATE
}
```

**Comment by zhusulai** [comment]
Just ran into this as well and I used ARM template to work around the issue. For creating DNS records, the private IP of the endpoint can be retrieved using `azurerm_private_endpoint_connection` data source.

**Comment by brownz11** [comment]
Also looking to deploy this into our environment. In our case however we're not Snowflake users so it's not limited to just Snowflake users

**Comment by grayzu** [comment]
As of the latest release of the provider (v 2.55.0 ), you should be able to use the [private_connection_resource_alias](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint#private_connection_resource_alias) property instead of the private_connection_resource_id property to achieve this.

**Comment by grayzu** [comment]
Closing this issue as it has been resolved by [PR 10779](https://github.com/terraform-providers/terraform-provider-azurerm/pull/10779)

**Comment by zhusulai** [comment]
I just tested 2.55.0 with `private_connection_resource_alias` but still getting the below error. Anybody seeing the same issue?

```
# module.azml.azurerm_private_endpoint.pe[0] will be created 
+ resource "azurerm_private_endpoint" "pe" { 
    + custom_dns_configs       = (known after apply) 
    + id                       = (known after apply) 
    + location                 = "eastus2" 
    + name                     = "[redacted]" 
    + private_dns_zone_configs = (known after apply) 
    + resource_group_name      = "[redacted]" 
    + subnet_id                = "[redacted]" 

    + private_service_connection { 
        + is_manual_connection              = false 
        + name                              = "[redacted]" 
        + private_connection_resource_alias = "[redacted].eastus2.azure.privatelinkservice" 
        + private_ip_address                = (known after apply) 
    }
}
```

`
"Property id '[redacted].eastus2.azure.privatelinkservice' at path 'properties.privateLinkServiceConnections[0].properties.privateLinkServiceId' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."
`

**Comment by markkeig** [comment]
Tested and working with 2.56.0, thanks for fixing

**Comment by Marcus-James-Adams** [comment]
You need to change it from service_id to service_alias.  I'm afk from my pc
right now but the provider resource definition shows the options

**Comment by zhusulai** [comment]
Answering my own questions - apparently, when using `private_connection_resource_alias`, the `is_manual_connection` flag has to be set to `true`. Also, `request_message` cannot be empty.
