### ISSUE TITLE
Azurerm 2.0: azurerm_linux_virtual_machine needs to be recreated

### ISSUE THREAD

**Issue by Mr-iX** [terraform-providers/terraform-provider-azurerm#5936]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20 and Azurerm 2.0.0

### Affected Resource(s)

* `azurerm_linux_virtual_machine`

### Terraform Configuration Files

New configuration:
```hcl
resource "azurerm_linux_virtual_machine" "dns-vm" {
  count                            = "2"
  name                             = "dns${count.index+1}"
  location                         = var.azure_location_short
  resource_group_name              = azurerm_resource_group.resource_group.name
  size                             = "Standard_B1S"
  network_interface_ids            = [element(azurerm_network_interface.dns-nic.*.id, count.index)]
  zone                             = element("${list("1","2","3")}", count.index)
  computer_name                    = "dns${count.index+1}"
  disable_password_authentication  = true
  admin_username                   = var.os_user

  source_image_reference {
    publisher = "OpenLogic"
    offer     = "CentOS"
    sku       = "7.6"
    version   = "latest"
  }

  boot_diagnostics {
    storage_account_uri = "https://${azurerm_storage_account.diag.name}.blob.core.windows.net/"
  }

  os_disk {
    name                 = "dns${count.index+1}_OsDisk"
    caching              = "ReadWrite"
    disk_size_gb         = "128"
    storage_account_type = "Standard_LRS"
  }

  admin_ssh_key {
    username   = var.os_user
    public_key = file("${path.module}/certs/ssh.pub")
  }

  tags = merge(
    var.tags,
    {
      "type" = "dns"
    },
  )
}
```

Old configuration:
```hcl
resource "azurerm_virtual_machine" "dns-vm" {
  count                            = "2"
  name                             = "dns${count.index+1}"
  location                         = var.azure_location_short
  resource_group_name              = azurerm_resource_group.resource_group.name
  vm_size                          = "Standard_B1S"
  network_interface_ids            = [element(azurerm_network_interface.dns-nic.*.id, count.index)]
  delete_data_disks_on_termination = "false"
  delete_os_disk_on_termination    = "false"
  zones                            = list("${element("${list("1","2","3")}", count.index)}")

  os_profile {
    computer_name  = "dns${count.index+1}"
    admin_username = var.os_user
    admin_password = var.os_password
  }

  storage_image_reference {
    publisher = "OpenLogic"
    offer     = "CentOS"
    sku       = "7.6"
    version   = "latest"
  }

  boot_diagnostics {
    enabled     = "true"
    storage_uri = "https://${azurerm_storage_account.diag.name}.blob.core.windows.net/"
  }

  os_profile_linux_config {
    disable_password_authentication = true
    ssh_keys {
      path     = "/home/${var.os_user}/.ssh/authorized_keys"
      key_data = file("${path.module}/certs/ssh.pub")
    }
  }

  storage_os_disk {
    name              = "dns${count.index+1}_OsDisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    os_type           = "Linux"
    disk_size_gb      = "128"
    managed_disk_type = "Standard_LRS"
  }

  tags = merge(
    var.tags,
    {
      "type" = "dns"
    },
  )
}
```

### Expected Behavior

I tried to update my `azurerm_virtual_machine` resources to new Azurerm 2.0 `azurerm_linux_virtual_machine` resource. So I modified all the configuration to the new resources (see above) and remove the old VMs from my state and imported them again.
```shell
terraform state rm 'azurerm_virtual_machine.dns-vm[0]'
terraform state rm 'azurerm_virtual_machine.dns-vm[1]'

terraform import 'azurerm_linux_virtual_machine.dns-vm[0]' /subscriptions/[ID]/resourceGroups/[RG]/providers/Microsoft.Compute/virtualMachines/dns1
terraform import 'azurerm_linux_virtual_machine.dns-vm[1]' /subscriptions/[ID]/resourceGroups/[RG]/providers/Microsoft.Compute/virtualMachines/dns2
```

The problem is that Terraform wants to recreate the VMs, because something changed:
```
  # azurerm_linux_virtual_machine.dns-vm[0] must be replaced
-/+ resource "azurerm_linux_virtual_machine" "dns-vm" {
        admin_username                  = "user"
        allow_extension_operations      = true
        computer_name                   = "dns1"
        disable_password_authentication = true
      ~ id                              = "/subscriptions/[ID]/resourceGroups/[RG]/providers/Microsoft.Compute/virtualMachines/dns1" -> (known after apply)
        location                        = "westeurope"
        max_bid_price                   = -1
        name                            = "dns1"
        network_interface_ids           = [
            "/subscriptions/[ID]/resourceGroups/[RG]/providers/Microsoft.Network/networkInterfaces/dns1-nic",
        ]
      + priority                        = "Regular" # forces replacement
      ~ private_ip_address              = "[IP]" -> (known after apply)
      ~ private_ip_addresses            = [
          - "[IP]",
        ] -> (known after apply)
        provision_vm_agent              = true
      + public_ip_address               = (known after apply)
      ~ public_ip_addresses             = [] -> (known after apply)
        resource_group_name             = "[RG]"
        size                            = "Standard_B1S"
        tags                            = {
            "managedBy" = "terraform"
            "owner"     = "coc-dit"
            "type"      = "dns"
        }
      ~ virtual_machine_id              = "[ID]" -> (known after apply)
        zone                            = "1"

        admin_ssh_key {
            public_key = <<~EOT
                ssh-rsa [pub-key] == user
            EOT
            username   = "user"
        }

        boot_diagnostics {
            storage_account_uri = "https://diag.blob.core.windows.net/"
        }

      ~ os_disk {
            caching                   = "ReadWrite"
            disk_size_gb              = 128
            name                      = "dns1_OsDisk"
            storage_account_type      = "Standard_LRS"
            write_accelerator_enabled = false
        }

        source_image_reference {
            offer     = "CentOS"
            publisher = "OpenLogic"
            sku       = "7.6"
            version   = "latest"
        }

      - timeouts {}
    }
```

So how can I convert my existing `azurerm_virtual_machine` VMS to `azurerm_linux_virtual_machine` VMs?

### Actual Behavior

Import VMs without the need of a recreation

### Steps to Reproduce

1. Update configuration
2. Delete old VMs from state
3. Import VMs again
4. Run `terraform plan`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @Mr-iX 

Taking a look at the diff here:

```
      + priority                        = "Regular" # forces replacement
```

The field `priority` is missing from the resource posted above - as such adding this field/value to the Terraform Configuration should resolve this, would you be able to take a look? Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by Mr-iX** [comment]
Thanks @tombuildsstuff 
The problem still persists and I think the import is not working correctly, thats why I have opened a issue instead of a question.

Also the import of `azurerm_managed_disk` imports the resource group name in uppercase and not like it looks in Azure (lowercase)
```hcl
-/+ resource "azurerm_linux_virtual_machine" "dns-vm" {
        admin_username                  = "automatix"
        allow_extension_operations      = true
        computer_name                   = "dns1"
        disable_password_authentication = true
      ~ id                              = "/subscriptions/[ID]/resourceGroups/management-hub-1eu1-a/providers/Microsoft.Compute/virtualMachines/dns1" -> (known after apply)
        location                        = "westeurope"
        max_bid_price                   = -1
        name                            = "dns1"
        network_interface_ids           = [
            "/subscriptions/[ID]/resourceGroups/management-hub-1eu1-a/providers/Microsoft.Network/networkInterfaces/dns1-nic",
        ]
      + priority                        = "Regular" # forces replacement
      ~ private_ip_address              = "ip" -> (known after apply)
      ~ private_ip_addresses            = [
          - "100.66.16.4",
        ] -> (known after apply)
        provision_vm_agent              = true
      + public_ip_address               = (known after apply)
      ~ public_ip_addresses             = [] -> (known after apply)
        resource_group_name             = "management-hub-1eu1-a"
        size                            = "Standard_B1S"
        tags                            = {
            "managedBy" = "terraform"
            "owner"     = "coc-dit"
            "type"      = "dns"
        }
      ~ virtual_machine_id              = "id" -> (known after apply)
        zone                            = "1"

        admin_ssh_key {
            public_key = <<~EOT
                ssh-rsa key automation
            EOT
            username   = "user"
        }

        boot_diagnostics {
            storage_account_uri = "https://id.blob.core.windows.net/"
        }

      ~ os_disk {
            caching                   = "ReadWrite"
            disk_size_gb              = 128
            name                      = "dns1_OsDisk"
            storage_account_type      = "Standard_LRS"
            write_accelerator_enabled = false
        }

        source_image_reference {
            offer     = "CentOS"
            publisher = "OpenLogic"
            sku       = "7.6"
            version   = "latest"
        }

      - timeouts {}
    }

  # azurerm_managed_disk.registry must be replaced
-/+ resource "azurerm_managed_disk" "registry" {
        create_option        = "Empty"
      ~ disk_iops_read_write = 7500 -> (known after apply)
      ~ disk_mbps_read_write = 250 -> (known after apply)
        disk_size_gb         = 2000
      ~ id                   = "/subscriptions/[ID]/resourceGroups/MANAGEMENT-HUB-1EU1-A/providers/Microsoft.Compute/disks/registry_DataDisk" -> (known after apply)
        location             = "westeurope"
        name                 = "registry_DataDisk"
      ~ resource_group_name  = "MANAGEMENT-HUB-1EU1-A" -> "management-hub-1eu1-a" # forces replacement
      + source_uri           = (known after apply)
        storage_account_type = "Premium_LRS"
        tags                 = {
            "managedBy" = "terraform"
            "owner"     = "coc-dit"
            "type"      = "harbor"
        }
        zones                = [
            "1",
        ]

      - timeouts {}
    }

  # azurerm_virtual_machine_data_disk_attachment.capsule-disk-attach must be replaced
-/+ resource "azurerm_virtual_machine_data_disk_attachment" "capsule-disk-attach" {
      ~ caching                   = "None" -> "ReadWrite"
      ~ create_option             = "Empty" -> "Attach" # forces replacement
      ~ id                        = "/subscriptions/[ID]/resourceGroups/management-hub-1eu1-a/providers/Microsoft.Compute/virtualMachines/katello-capsule/dataDisks/katello-capsule_DataDisk" -> (known after apply)
        lun                       = 0
      ~ managed_disk_id           = "/subscriptions/[ID]/resourceGroups/MANAGEMENT-HUB-1EU1-A/providers/Microsoft.Compute/disks/katello-capsule_DataDisk" -> (known after apply) # forces replacement
      ~ virtual_machine_id        = "/subscriptions/[ID]/resourceGroups/management-hub-1eu1-a/providers/Microsoft.Compute/virtualMachines/katello-capsule" -> (known after apply) # forces replacement
        write_accelerator_enabled = false

      - timeouts {}
    }
```

**Comment by jomeier** [comment]
Hi,

same problem here.

@tombuildsstuff:
Thanks for releasing version 2 of this provider. I love the timeout feature. It solves lots of problems that we currently have. Congrats!

Could you and your team help us in fixing this bugs, please?

Thanks a lot and greetings,

Josef
