### ISSUE TITLE
the default value of load_balancer_sku is not standard if network_profile is not specified

### ISSUE THREAD

**Issue by bingosummer** [terraform-providers/terraform-provider-azurerm#6132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.23

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
esource "azurerm_kubernetes_cluster" "example" {
  name                 = "myclustername"
  location             = var.location
  resource_group_name  = var.rg_name
  dns_prefix           = "myclusternamedns"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  service_principal {
    client_id     = var.client_id
    client_secret = var.client_secret
  }

  tags = {
    Environment = "Production"
  }
}

output "client_certificate" {
  value = azurerm_kubernetes_cluster.example.kube_config.0.client_certificate
}

output "kube_config" {
  value = azurerm_kubernetes_cluster.example.kube_config_raw
}
```

### Expected Behavior

The load balancer should be standard.

### Actual Behavior

If we don't specify the network_profile, then the load_balancer_sku is set to basic.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jluk** [comment]
This was a change brought in the v2.0.0 release

https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v2.0.0

**Comment by tombuildsstuff** [comment]
hey @bingosummer 

Thanks for opening this issue.

As @jluk has mentioned this issue's been fixed in version 2.0 of the Azure Provider where the default value's been changed from Basic -> Standard - as such you should be able to resolve this (for a new cluster) by upgrading to this release.

Since this should be fixed by updating to version 2.0 (or later - the current version is 2.3) of the Azure Provider I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by rgl** [comment]
There is a bug somewhere. Either its the documentation or this provider, because I'm using 2.3.0 and I still have a Basic sku.

The [documentation at states that the default load balancer sku is Standard](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#load_balancer_sku):

> load_balancer_sku - (Optional) Specifies the SKU of the Load Balancer used for this Kubernetes Cluster. Possible values are Basic and Standard. Defaults to Standard.

But its actually Basic:

![image](https://user-images.githubusercontent.com/43356/78457229-997a5e80-76a0-11ea-97ff-1e6a11f0d854.png)

I'm using this provider v2.3.0 and my `azurerm_kubernetes_cluster` resource is at https://github.com/rgl/terraform-azure-aks-example/blob/7600bc739a50a926f1fc309a04ba0baca8eeb1f4/main.tf#L97-L149

**Comment by helgart007** [comment]
@tombuildsstuff The problem still exists in version 2.7.0. Documentation states that "Standard" is the default value. But it actually is "Basic" when network_profile section is not specified.
