### ISSUE TITLE
source_image_reference documentation missing for azurerm_linux_virtual_machine and azurerm_windows_virtual_machine

### ISSUE THREAD

**Issue by NilsBusche** [terraform-providers/terraform-provider-azurerm#6403]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Detailed documentation for `source_image_reference` is missing in the documentation for virtual machines. 

In the documentation is the general description for `source_image_reference` but the mentioned detailed description for this block is missing.

### New or Affected Resource(s)

`azurerm_linux_virtual_machine`
`azurerm_windows_virtual_machine`

**Comment by kinwolfqc** [comment]
Did you mean storage_image_reference?

**Comment by kinwolfqc** [comment]
I was coming here because I want to use a custom image made with packer in azure and could not find a way.  Where can we see how it is done?

**Comment by dhabierre** [comment]
Any feedback?

**Comment by mhaarbrink** [comment]
Additionally this needs to be defined in the virtual machine scale set articles
https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine_scale_set.html
https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine_scale_set.html

The source_image_id and source_image_reference should have descriptive information identifying if there is a dependency on a shared image gallery or if either can be used for public gallery images as well.

**Comment by tombuildsstuff** [comment]
Fixed via #6833

**Comment by mhaarbrink** [comment]
> 
> 
> Fixed via #6918

How long does it usually take for the change to reflect on the website once it's merged?  Looking just now I still don't see those blocks but I do see that change was merged.

**Comment by tombuildsstuff** [comment]
@mhaarbrink it'll go out with the next release, which should be later today :)
