### ISSUE TITLE
  azurerm_mysql_server: ssl_minimal_tls_version_enforced is ignored

### ISSUE THREAD

**Issue by MikeMichel** [terraform-providers/terraform-provider-azurerm#7228]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
2.13.0

### Affected Resource(s)
* `azurerm_mysql_server`

### Expected Behavior

I want to use: 
```hcl
  ssl_enforcement_enabled           = true
  ssl_minimal_tls_version_enforced  = "TLS1_2"
```
terraform apply shows:
```
~ ssl_minimal_tls_version_enforced  = "TLSEnforcementDisabled" -> "TLS1_2"
```
but in azure portal nothing changes and another terraform apply shows again
```
~ ssl_minimal_tls_version_enforced  = "TLSEnforcementDisabled" -> "TLS1_2"
```

minimal tls version should be changed

### Actual Behavior
it stays disabled

### Steps to Reproduce

1. `terraform apply`

**Comment by yupwei68** [comment]
Hi @MikeMichel , thanks for opening this issue. I'm fixing this.

**Comment by jrmilholland** [comment]
This is also broken for azurerm_postgresql_server.

**Comment by yupwei68** [comment]
Hi @MikeMichel , I think this problem has been fixed by Tom's PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/6809, which has been released in v2.18.0

**Comment by jackofallops** [comment]
Hi @MikeMichel 
I've done some testing on the 2.18 release and this does appear to be resolved now as mentioned by @yupwei68 (see below).  I'm going to close this issue for now, but if you still experience this issue using 2.18 we can re-open it.

![image](https://user-images.githubusercontent.com/11830746/87130027-29c0d480-c28a-11ea-9389-3cbfe36f65c4.png)

![image](https://user-images.githubusercontent.com/11830746/87129863-e9615680-c289-11ea-82c3-4520b71b35f0.png)

Thanks

**Comment by jackofallops** [comment]
Update: this is only fixed for create operations, the bug remains in updates, should be fixed by #7307 which should be in 2.19.0 of the provider.
